import React from "react";
import Head from "next/head";
import useMediaQuery from "@mui/material/useMediaQuery";
import MainLayout from "../layouts/MainLayout";
import Kanban from "../components/pages/kanban";

export default function Home() {
  return (
    <MainLayout>
      <div>
        <Head>
          <title>Kanban</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicons/72x72.png" />
        </Head>
        <Kanban />
      </div>
    </MainLayout>
  );
}
