import React from "react";
import Head from "next/head";
import Grid from "@mui/material/Grid";
import Box from "@mui/material/Box";
import Link from "@mui/material/Link";
import Card from "@mui/material/Card";
import CardHeader from "@mui/material/CardHeader";
import CardContent from "@mui/material/CardContent";
import Typography from "@mui/material/Typography";
import Button from "@mui/material/Button";
import List from "@mui/material/List";
import styles from "../../styles/Home.module.css";
import MainLayout from "../layouts/MainLayout";
import Dialog from "../components/Dialog";
import Alert from "../components/Alert";
import GetCountriesQuery from "../api/graphQueries/GetCountries";
import ListShimmers from "../components/shimmers/ListShimmers";
import CountriesListItem from "../components/pages/homeComponents/CountriesListItem";
import CountrySearchTextField from "../forms/Home/CountrySearchTextField";

export default function Home() {
  const [searchParam, setSearchParam] = React.useState("");
  const [dialogDetails, setDialogDetails] = React.useState({
    open: false,
    country: "",
  });
  const handleChange = (event) => {
    setSearchParam(event.target.value);
  };
  const selectOption = (value) => {
    setDialogDetails({ open: true, country: value });
  };
  const closeDialog = () => {
    setDialogDetails({ open: false, country: "" });
  };
  const { open, country } = dialogDetails;
  return (
    <MainLayout>
      <Dialog
        open={open}
        maxWidth="xs"
        modalContent={
          <div className="center">
            <Typography variant="body1">
              You have selected <strong>{country}</strong>.
            </Typography>
            <Box mt={1}>
              <Button variant="contained" color="primary" onClick={closeDialog}>
                Close
              </Button>
            </Box>
          </div>
        }
        handleClose={closeDialog}
      />
      <div>
        <Head>
          <title>Next Js Boilerplate Starter pack</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicons/72x72.png" />
        </Head>
        <Grid container spacing={2} className={styles.main}>
          <Grid item lg={3} xl={3} />
          <Grid item lg={6} xl={6} sm={12} xs={12}>
            <Typography
              variant="h1"
              sx={{
                fontSize: 35,
              }}
            >
              Welcome to{" "}
              <Link href="https://nextjs.org" target="_blank">
                Next.js!
              </Link>
            </Typography>
            <Box mt={1}>
              <Typography variant="body1" className={styles.description}>
                Get started by editing{" "}
                <code className={styles.code}>pages/index.js</code>
              </Typography>
            </Box>
          </Grid>
          <Grid item lg={3} xl={3} />
          <Grid item lg={3} xl={3} />
          <Grid item lg={6} xl={6} sm={12} xs={12}>
            <Card style={{ width: "100%" }}>
              <CardHeader
                title="Countries"
                sx={{
                  "& span": {
                    fontSize: 20,
                  },
                }}
              />
              <CardContent>
                <CountrySearchTextField handleChange={handleChange} />
                <Box
                  sx={{
                    maxHeight: 300,
                    overflow: "scroll",
                  }}
                >
                  <GetCountriesQuery
                    variables={{ param: searchParam }}
                    loader={<ListShimmers />}
                  >
                    {({ getCountries }) => (
                      <div>
                        {getCountries.length > 0 ? (
                          <List>
                            {getCountries.map((item) => (
                              <CountriesListItem
                                key={item.country}
                                item={item}
                                selectOption={selectOption}
                              />
                            ))}
                          </List>
                        ) : (
                          <Alert severity="warning">
                            Sorry we do not have any countries
                          </Alert>
                        )}
                      </div>
                    )}
                  </GetCountriesQuery>
                </Box>
              </CardContent>
            </Card>
          </Grid>
          <Grid item lg={3} xl={3} />
        </Grid>
      </div>
    </MainLayout>
  );
}
