import React from "react";
import Head from "next/head";
import { makeStyles } from "@material-ui/core/styles";
import { Grid, Typography, Box, Link } from "@material-ui/core";
import styles from "../styles/Home.module.css";
import MainLayout from "../src/layouts/MainLayout";

const useStyles = makeStyles((theme) => ({
  heading: {
    fontSize: 35,
  },
  card: {
    border: "1px solid #eaeaea",
    borderRadius: 10,
    padding: 15,
  },
  cardLink: {
    color: theme.palette.text.primary,
    width: "100%",
    textDecoration: "none",
  },
}));
export default function Home() {
  const classes = useStyles();
  return (
    <MainLayout>
      <div>
        <Head>
          <title>Next Js Boilerplate Starter pack</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicons/72x72.png" />
        </Head>
        <Grid container spacing={2} className={styles.main}>
          <Grid item lg={3} xl={3} />
          <Grid item lg={6} xl={6} sm={12} xs={12}>
            <Typography variant="h1" className={classes.heading}>
              Welcome to{" "}
              <Link href="https://nextjs.org" target="_blank">
                Next.js!
              </Link>
            </Typography>
            <Box mt={1}>
              <Typography variant="body1" className={styles.description}>
                Get started by editing{" "}
                <code className={styles.code}>pages/index.js</code>
              </Typography>
            </Box>
          </Grid>
          <Grid item lg={3} xl={3} />
          <Grid item lg={3} xl={3} />
          <Grid item lg={6} xl={6} sm={12} xs={12}>
            <Grid container spacing={2}>
              <Grid item lg={6} xl={6} sm={6} xs={12}>
                <div className={classes.card}>
                  <Link
                    href="https://nextjs.org/docs"
                    target="_blank"
                    className={classes.cardLink}
                  >
                    <Typography variant="h3">Documentation &rarr;</Typography>
                    <Box mt={1}>
                      <Typography variant="body1">
                        Find in-depth information about Next.js features and
                        API.
                      </Typography>
                    </Box>
                  </Link>
                </div>
              </Grid>
              <Grid item lg={6} xl={6} sm={6} xs={12}>
                <div className={classes.card}>
                  <Link
                    href="https://nextjs.org/learn"
                    target="_blank"
                    className={classes.cardLink}
                  >
                    <Typography variant="h3">Learn &rarr;</Typography>
                    <Box mt={1}>
                      <Typography variant="body1">
                        Discover and deploy boilerplate example Next.js
                        projects.
                      </Typography>
                    </Box>
                  </Link>
                </div>
              </Grid>
            </Grid>
          </Grid>
          <Grid item lg={3} xl={3} />
        </Grid>
      </div>
    </MainLayout>
  );
}
